/*
 * This file was generated by node-ffi-packager v1.0.0.
 * https://github.com/node-ffi-packager
 *
 * Library: libjpeg
 * Conan.io recipe reference: libjpeg/9d
 * Conan.io remote: conan-center
 * Conan.io package id: 127af201a4cdf8111e2e08540525c245c9b3b99e
 */

const { loadLibrary } = require("../loader");

const input = require("./index.json");

module.exports = {
  // NOTE: named wrapper function with library name prefix to make it easier to spot in a stack trace.
  // NOTE: assumes that the library name is in a suitable format.
  load: async function libjpegLibraryLoader() {
    return loadLibrary(__dirname, input);
  },
};
