/*
 * This file was generated by node-ffi-packager v1.0.0.
 * https://github.com/node-ffi-packager
 *
 * Library: libjpeg
 * Conan.io recipe reference: libjpeg/9d
 * Conan.io remote: conan-center
 * Conan.io package id: 92b19409f9d1b1cd1ae7699ecc60ac44fc3e4f69
 */

const { loadLibrary } = require("../loader");

const input = require("./index.json");

module.exports = {
  // NOTE: named wrapper function with library name prefix to make it easier to spot in a stack trace.
  // NOTE: assumes that the library name is in a suitable format.
  load: async function libjpegLibraryLoader() {
    return loadLibrary(__dirname, input);
  },
};
